### ISSUE TITLE
Will not connect to Google Fit

### ISSUE THREAD

**Issue by PanHyridae** [googlesamples/android-play-games-in-motion#1]
The app will not connect to Google Fit. This could be due to a missing INTERNET permission, but not even this fixes the problem.

**Comment by omegasoft7** [comment]
i have the same problem!!!!

and here are my logs:

05-07 17:07:33.690  21658-21658/com.google.fpl.gim.examplegame D/MainActivity﹕ onCreate
05-07 17:07:33.720  21658-21658/com.google.fpl.gim.examplegame D/MainActivity﹕ onStart
05-07 17:07:33.730  21658-21658/com.google.fpl.gim.examplegame D/MainActivity﹕ onResume
05-07 17:07:33.730  21658-21658/com.google.fpl.gim.examplegame D/MainService﹕ onCreate
05-07 17:07:33.740  21658-21658/com.google.fpl.gim.examplegame I/TextToSpeech﹕ Sucessfully bound to com.samsung.SMT
05-07 17:07:33.740  21658-21658/com.google.fpl.gim.examplegame V/MediaPlayer-JNI﹕ native_setup
05-07 17:07:33.740  21658-21658/com.google.fpl.gim.examplegame V/MediaPlayer﹕ constructor
05-07 17:07:33.740  21658-21658/com.google.fpl.gim.examplegame V/MediaPlayer﹕ setListener
05-07 17:07:33.740  21658-21658/com.google.fpl.gim.examplegame D/MainService﹕ onStartCommand
05-07 17:07:33.740  21658-21658/com.google.fpl.gim.examplegame D/MainService﹕ onBind
05-07 17:07:33.760  21658-21658/com.google.fpl.gim.examplegame I/TextToSpeech﹕ Connected to ComponentInfo{com.samsung.SMT/com.samsung.SMT.SamsungTTSService}
05-07 17:07:33.760  21658-21658/com.google.fpl.gim.examplegame D/GoogleApiClientWrapper﹕ Building the Google Api Client.
05-07 17:07:33.760  21658-21658/com.google.fpl.gim.examplegame W/PopupManager﹕ You have not specified a View to use as content view for popups. Falling back to the Activity content view which may not work properly in future versions of the API. Use setViewForPopups() to set your content view.
05-07 17:07:33.770  21658-22990/com.google.fpl.gim.examplegame I/TextToSpeech﹕ Set up connection to ComponentInfo{com.samsung.SMT/com.samsung.SMT.SamsungTTSService}
05-07 17:07:33.820  21658-21658/com.google.fpl.gim.examplegame D/MainService﹕ TTS locale supported.
05-07 17:07:33.940  21658-21658/com.google.fpl.gim.examplegame E/GoogleApiClientWrapper﹕ Connection failed. Cause: ConnectionResult{statusCode=SIGN_IN_REQUIRED, resolution=PendingIntent{428fa068: android.os.BinderProxy@428bdb60}}
05-07 17:07:33.940  21658-21658/com.google.fpl.gim.examplegame D/GoogleApiClientWrapper﹕ Attempting to resolve failed connection
05-07 17:07:33.960  21658-21658/com.google.fpl.gim.examplegame D/MainActivity﹕ onPause
05-07 17:07:33.980  21658-21658/com.google.fpl.gim.examplegame D/MainService﹕ onUnbind
05-07 17:07:38.385  21658-21658/com.google.fpl.gim.examplegame D/MainActivity﹕ onResume
05-07 17:07:38.465  21658-21658/com.google.fpl.gim.examplegame D/MainService﹕ onRebind
05-07 17:07:38.505  21658-21658/com.google.fpl.gim.examplegame E/GoogleApiClientWrapper﹕ Connection failed. Cause: ConnectionResult{statusCode=SIGN_IN_REQUIRED, resolution=PendingIntent{42902a78: android.os.BinderProxy@428bdb60}}

**Comment by aliceching** [comment]
Here's the documentation for building:
https://github.com/googlesamples/android-play-games-in-motion/blob/master/docs/src/programmers_guide/building.md

Please set up Google Play Games services via the Dev Console, because the
app is not on the Play Store.

Hope this helps!

Alice Ching | Software Engineer | aliceching@google.com |

**Comment by tonyjhuang** [comment]
Just wondering, what's stopping you from releasing to the Play Store? I'm sure your app would get a lot more testers/users if you didnt have to set up a new app in the API console just to try it.

**Comment by keyboardsurfer** [comment]
This is a developer sample. Currently we do not release these in a compiled way.
Please refer to [Alice's link](https://github.com/googlesamples/android-play-games-in-motion/blob/master/docs/src/programmers_guide/building.md) to build this sample correctly.
